# Generated by Django 5.0.6 on 2024-05-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, db_index=True, max_length=15, null=True
                    ),
                ),
                (
                    "member_id",
                    models.CharField(db_index=True, max_length=15, unique=True),
                ),
                ("date_of_birth", models.DateTimeField(blank=True, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
