# Generated by Django 5.0.6 on 2024-05-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("L", "Launched"),
                            ("P", "Planning"),
                            ("T", "Terminated"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
