# Generated by Django 5.0.6 on 2024-05-24 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(db_index=True, max_length=15, unique=True),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.members",
                    ),
                ),
                (
                    "offer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="offers.offers"
                    ),
                ),
            ],
        ),
    ]
